const placeholderSamples = [
    "Smartphone",
    "Laptop",
    "Tablet",
    "Television",
    "Smartwatch",
    "Speakers",
    "Headphones",
    "Camera",
    "Gaming console",
    "Vacuum cleaner",
    "Refrigerator",
    "Washing machine",
    "Dryer",
    "Fan",
    "Air conditioner",
    "Microwave",
    "Kitchen robot",
    "Blender",
    "Iron",
    "Hair dryer",
    "Trimmer",
    "Electric kettle",
    "Coffee maker",
    "Toaster",
    "Rice cooker",
    "Slow cooker",
    "Pressure cooker",
    "Sonic toothbrush",
    "Electric shaver",
    "Hair straightener",
    "Hair curler",
    "Makeup mirror",
    "Electric heater",
    "Air purifier",
    "Smart lock",
    "Security camera",
    "Smart home hub",
    "Smart plug",
    "LED light strip",
    "Smart bulb",
    "Smart thermostat",
    "Smart scale",
    "Smart smoke detector",
    "Smart doorbell",
    "Smart lock",
    "Smart home security system",
    "Action camera",
    "Drone",
    "E-reader",
    "Fitness tracker",
    "Smart fitness equipment",
    "Wireless charger",
    "Power bank",
    "Portable battery",
    "External hard drive",
    "Flash drive",
    "Memory card",
    "Wireless mouse",
    "Keyboard",
    "Laptop stand",
    "Webcam",
    "External drive",
    "Printer",
    "Ink cartridge",
    "Toner cartridge",
    "Paper",
    "Office chair",
    "Office desk",
    "File cabinet",
    "Bookshelf",
    "Briefcase",
    "Backpack",
    "Luggage",
    "Duffel bag",
    "Gym bag",
    "Tote bag",
    "Purse",
    "Wallet",
    "Phone case",
    "Screen protector",
    "Headphone case",
    "Stylus pen"
];

export default placeholderSamples;